version: '3.4'

services:

  db:
    image: mysql
    network_mode: bridge
    container_name: apiclienteDB
    
    expose:
      - 3307:3307
    ports:
      - 3307:3307
    environment:
      - MYSQL_HOST=172.17.0.2
      - MYSQL_PORT=3307
      - MYSQL_PASSWORD=M@theusleticia25
      - MYSQL_DATABASE=apiclienteDB
      - MYSQL_IP_ADDRESS=172.17.0.2
      - MYSQL_ROOT_PASSWORD=M@theusleticia25
     
      
  apicliente:
    image: apicliente
    network_mode: bridge
    
    build: .
  
    expose:
      - 8080
    ports:
      - 8080:8080
   
    environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.2:3306/apiclienteDB
    depends_on:
       - db
      


