version: 2.1

orbs:
  maven: circleci/maven@1.0.3

workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: api-cliente
          test_results_path: api-cliente/target/surefire-reports